### ISSUE TITLE
Ajeitar diagrama de classes

### ISSUE THREAD

**Issue by milenasiqs** [ifpe-cti/doAcao#48]
<img width="522" alt="diagrama de classe" src="https://user-images.githubusercontent.com/26824725/48721610-05217000-ec01-11e8-9f61-b7dde9477a3a.png">

**Comment by fabriciofx** [comment]
@milenasiqs Aceitas algumas sugestões?
1. Dá uma olhada nos nomes do atributos da interface `RequisiçãoDeExames`: `nomeDoador`, `numeroDeDocumentoDoador`, `tipoDeDocumentoDoador`, etc. Geralmente (para não dizer sempre) quando temos atributos com nomes compostos, isto significa que há uma outra entidade querendo "emergir" (aparecer) no modelo. Ao meu ver, há a necessidade de se criar uma entidade `Doador` no seu modelo, que este é que terá `nome`, `nomePai`, `nomeMãe`, etc. Também veja os atributos `numeroDeDocumentoDoador`, `tipoDeDocumentoDoador`. Isso me indica que há um outro objeto que precisa ser criado `Documento` que terá `numero` e `tipo` e que fará parte da entidade `Doador`.
2. Também dá uma olhada em `AgendamentoDoacao`. Está vendo o atributo `dataAgendamento`? Se é um atributo de `AgendamentoDoacao`, não precisa ter o nome `Agendamento`, portanto pode ser chamado apenas de `data`. Aliás, por que  `AgendamentoDoacao` tem esse nome? É feito algum agendamento que não seja para doação? Se não, que tal chamar apenas de `Agendamento`? Caso tenho outros tipos de ações que não seja a doação, que tal colocar algum atributo que identifique qual ação (doação, etc) será realizada?

**Comment by milenasiqs** [comment]
@fabriciofx aceito sim. Muito obrigada pelas sugestões! Irei avaliar junto da equipe as possíveis alterações.

**Comment by fabriciofx** [comment]
@milenasiqs Sobre o ponto 3, o correto é ter os dois: interfaces e classes. Mas procure começar pelas interfaces. As classes são implementações das interfaces (as interfaces dizem o comportamento; as classes dizem *como* vão realizar este comportamento. Exemplo: uma `Pessoa` `sobe()`. Como esta pessoa irá "subir" -  escadas, elevador, escada rolante, será a classe que vai dizer/realizar).

**Comment by milenasiqs** [comment]
-Só coisas que não se relacionam com o bd entra no diagrama
-Fazer as relações entre as classes
-Colocar atributo e tipo

**Comment by fabriciofx** [comment]
@milenasiqs Uma coisa muito comum pra quem está aprendendo o paradigma OO é misturar dados com comportamento, fazendo assim um sistema voltado a dados e não a classes. Em suma: pensam que uma classe é uma tabela do banco de dados, quando na verdade não têm nada a ver. Assim, muito cuidado na hora da escolha dos atributos, bem como das relações com as classes. #ficaadica

**Comment by fabriciofx** [comment]
@milenasiqs Eita... agora que vi que você apagou meu comentário... 👍

**Comment by milenasiqs** [comment]
@fabriciofx tive uma reunião com Léo hoje pela manhã e vimos cada sugestão
sua e modificamos no projeto grande parte do que você sugeriu. Eu ia fechar
essa issue e abrir outra, então preferi editar e comentar as alterações que
eu vou fazer.

Em qua, 28 de nov de 2018 16:32, Fabricio Cabral <notifications@github.com
escreveu:

**Comment by milenasiqs** [comment]
@fabriciofx foi isso que Léo me disse hoje de manhã. Portanto, vou
modificar o diagrama atentando para essas informações

Em qua, 28 de nov de 2018 16:31, Fabricio Cabral <notifications@github.com
escreveu:

**Comment by fabriciofx** [comment]
@milenasiqs Mas não se apaga comentários das issues. Eles fazem parte do histórico da evolução do seu software. Devem servir (ou não) para futuras consultas. O que poderia/deveria ser feito:
1. Nesta mesma issue, escrever um comentário dizendo que de acordo com as minhas sugestões e com a reunião com o orientador, ficou definido em se fazer isso, isso e aquilo;
2. Ter fechado esta issue e ter aberto outra, referenciando esta.
Note, que de um modo geral, deletar dados *sejam eles quais forem* não é um boa polícia para nenhuma aplicação, pois elas fazem parte do histórico/evolução do sistema como um todo.
