### ISSUE TITLE
Comunicação com o banco de sangue

### ISSUE THREAD

**Issue by milenasiqs** [ifpe-cti/doAcao#6]
Como receptor desejo que comunicar com o banco de sangue para achar doadores ou ver o banco de sangue com cada tipo disponível.

**Comment by joannegabriela** [comment]
Quebrar em issues menores 
* Usuário se comunica com o hemocentro
* Hemocentro valida o pedido 
* Hemocentro se comunica com todos os outros usuários que tenham sangue do tipo necessitado
*Hemocentro envia uma mensagem para o usuário que solicitou o recebimento
